import { Database } from '../database/database';
import { QueryBuilder } from '../../query-builder/query-builder';
import type { FindOptions } from '../../query-builder/types';
import { IncompletePrimaryKeyError } from './repository.errors';
import { isAutoGeneratedType } from '../sql-types/sql-types';
import { sqlJoin } from '../utils/utils';
import type { ColumnMetadata } from '../metadata/metadata';

export class Repository<T> {
  constructor(
    private entity: new () => T,
    private db: Database,
  ) {}

  private requirePrimaryKey(
    key: Partial<T>,
    allowMissing?: (col: ColumnMetadata) => boolean,
  ): ColumnMetadata[] {
    const meta = this.db.getMetadata().get(this.entity)!;
    const primaryColumns = meta.columns.filter((c) => c.primary);
    const required = allowMissing
      ? primaryColumns.filter((c) => !allowMissing(c))
      : primaryColumns;
    const missing = required
      .map((pc) => pc.propertyName)
      .filter((prop) => !(prop in key));
    if (missing.length > 0) {
      throw new IncompletePrimaryKeyError(this.entity.name, missing);
    }
    return primaryColumns;
  }

  async findMany(options?: FindOptions<T>): Promise<T[]> {
    return new QueryBuilder<T>(this.entity, this.db).applyOptions(options).getMany();
  }

  async findOne(options?: FindOptions<T>): Promise<T | null> {
    return new QueryBuilder<T>(this.entity, this.db).applyOptions(options).getOne();
  }

  async findById(key: Partial<T>): Promise<T | null> {
    const primaryColumns = this.requirePrimaryKey(key);

    return new QueryBuilder<T>(this.entity, this.db)
      .applyOptions({
        where: (u) =>
          primaryColumns.map((pc) => {
            const prop = pc.propertyName as keyof T;
            return u[prop]?.eq(key[prop]!);
          }),
      })
      .getOne();
  }

  /**
   * Insert a row and return a key object containing every primary-key column.
   *
   * Required input:
   * - For non-auto-generated primary-key columns (any column whose `type` is
   *   not `SERIAL` / `SMALLSERIAL` / `BIGSERIAL`), the caller MUST supply a
   *   value in `entity`. Missing required PKs throw `IncompletePrimaryKeyError`.
   * - For auto-generated primary-key columns, the caller MAY omit the value
   *   (the database supplies it) or MAY supply an explicit value to override
   *   the auto-generation — the explicit value is written to the INSERT and
   *   echoed back in the returned key. Use overrides for data migrations,
   *   seeded fixtures, or restoring backups with stable IDs.
   * - Non-PK fields are not validated by this method; the database's NOT NULL
   *   constraints catch missing required columns at insert time.
   *
   * @returns A `Partial<T>` containing every primary-key column populated from
   *   the row's RETURNING result.
   * @throws {IncompletePrimaryKeyError} when a non-auto-generated primary-key
   *   column is missing from `entity`.
   */
  async create(entity: Partial<T>): Promise<Partial<T>> {
    const db = this.db;
    const meta = db.getMetadata().get(this.entity)!;
    const sql = db.getConnection();

    const primaryColumns = this.requirePrimaryKey(entity, (c) => isAutoGeneratedType(c.type));
    const nonPrimaryColumns = meta.columns.filter((c) => !c.primary);
    const tableName = sql(meta.tableName);

    const objectToInsert: Record<string, unknown> = {
      discriminator: meta.discriminator,
    };

    primaryColumns.forEach((col) => {
      const propertyName = col.propertyName as keyof T;
      if (propertyName in entity) {
        objectToInsert[col.columnName] = entity[propertyName];
      }
    });

    nonPrimaryColumns.forEach((col) => {
      const propertyName = col.propertyName as keyof T;
      objectToInsert[col.columnName] = entity[propertyName];
    });

    meta.relations.forEach((relation) => {
      const related = (entity as Record<string, unknown>)[relation.propertyName] as
        | Record<string, unknown>
        | null
        | undefined;

      relation.columns!.forEach((fk) => {
        objectToInsert[fk.name] = related == null ? null : related[fk.referencedProperty];
      });
    });

    const result = await sql<Record<string, unknown>[]>`
      INSERT INTO ${tableName} ${sql(objectToInsert)}
      RETURNING ${sqlJoin({ sql, items: primaryColumns, map: (pc) => sql`${sql(pc.columnName)}` })}
    `;

    const row = result[0]!;
    const key: Partial<T> = {};
    primaryColumns.forEach((pc) => {
      const prop = pc.propertyName as keyof T;
      key[prop] = row[pc.columnName] as T[keyof T];
    });
    return key;
  }

  async delete(key: Partial<T>): Promise<void> {
    const db = this.db;
    const meta = db.getMetadata().get(this.entity)!;
    const sql = db.getConnection();
    const tableName = sql(meta.tableName);
    const primaryColumns = this.requirePrimaryKey(key);

    const whereClause = sqlJoin({
      sql,
      items: primaryColumns,
      map: (pc) => sql`${sql(pc.columnName)} = ${key[pc.propertyName as keyof T]}`,
      separator: sql` AND `,
    });

    await sql`
      DELETE FROM ${tableName}
      WHERE ${whereClause}
    `;
  }

  async update(entity: T): Promise<void> {
    const db = this.db;
    const meta = db.getMetadata().get(this.entity)!;
    const sql = db.getConnection();

    const primaryColumns = meta.columns.filter((c) => c.primary);
    const columns = meta.columns.filter((c) => !c.primary);
    const tableName = sql(meta.tableName);

    const objectToUpdate: Record<string, unknown> = {};
    columns.forEach((col) => {
      const columnName = col.columnName;
      const propertyName = col.propertyName as keyof T;
      objectToUpdate[columnName] = entity[propertyName];
    });

    meta.relations.forEach((relation) => {
      const related = (entity as Record<string, unknown>)[relation.propertyName] as
        | Record<string, unknown>
        | null
        | undefined;

      relation.columns!.forEach((fk) => {
        objectToUpdate[fk.name] = related == null ? null : related[fk.referencedProperty];
      });
    });

    const whereClause = sqlJoin({
      sql,
      items: primaryColumns,
      map: (pc) => sql`${sql(pc.columnName)} = ${entity[pc.propertyName as keyof T]}`,
      separator: sql` AND `,
    });

    await sql`
      UPDATE ${tableName}
      SET ${sql(objectToUpdate)}
      WHERE ${whereClause}
    `;
  }
}
